// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include <Mib/SQL/SQL>
#include <Mib/Storage/Variant>
#include <Mib/Core/RuntimeType>

#ifdef DPlatformFamily_Windows
	#include <windows.h>
#endif

#include "../SourceGenerated/SQLite/sqlite3.h"

using namespace NMib;
using namespace NSQL;
using namespace NStr;
using namespace NContainer;
using namespace NMisc;
using namespace NStorage;

class CSQLiteQueryInstance;

class CSQLiteQuery : public CQuery
{
private:
	sqlite3_stmt* mp_pStatement;

	friend class CSQLiteQueryInstance;
public:

	CSQLiteQuery(sqlite3_stmt* _pStatement) : mp_pStatement(_pStatement)
	{
	}

	~CSQLiteQuery()
	{
		sqlite3_finalize(mp_pStatement);
		mp_pStatement = nullptr;
	}

	virtual NStorage::TCUniquePointer<CQueryInstance> f_CreateQueryInstance() override;
};

class CSQLiteQueryResult : public CQueryResult
{

public:

	typedef NMib::NStorage::TCVariant<int64, fp64, CStr> CValue;

	struct CRow
	{
		TCVector<CValue> m_Data;
	};

	aint m_nReturnedRows;
	aint m_nAffectedRows;
	aint m_nFields;
	uint64 m_iLastInsertedID;

	TCVector<CCol> m_Columns;
	TCVector<CRow> m_Rows;

public:
	CSQLiteQueryResult()
	{
		m_nReturnedRows = 0;
		m_nAffectedRows = 0;
		m_nFields = 0;
	}

//	virtual CStr const& f_GetString(int _iRow, int _iCol, CStr &_Dest)
	virtual CStr f_GetString(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return CStr();

		DMibRequire(m_Columns[_iCol].m_Type == EType_CStr);

		if (!m_Rows[_iRow].m_Data[_iCol].f_IsOfType<CStr>())
			return CStr();

		return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<CStr>();
	}

	virtual int64 f_GetInt64(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return 0;

		DMibRequire(m_Columns[_iCol].m_Type == EType_Int64);
		return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<int64>();
	}

	virtual fp64 f_GetFp64(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return 0;

		DMibRequire(m_Columns[_iCol].m_Type == EType_Fp64);
		return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<fp64>();
	}

	virtual bool f_IsNull(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		return m_Columns[_iCol].m_Type == EType_NULL;
	}

	virtual TCVector<CCol> const &f_GetFields()
	{
		return m_Columns;
	}

	virtual EType f_GetFieldType(int _iCol)
	{
		return m_Columns[_iCol].m_Type;
	}

	virtual CStr const &f_GetFieldName(int _iCol)
	{
		return m_Columns[_iCol].m_Name;
	}

	virtual aint f_NumReturnedRows()
	{
		return m_nReturnedRows;
	}

	virtual aint f_NumAffectedRows()
	{
		return m_nAffectedRows;
	}

	virtual aint f_NumFields()
	{
		return m_Columns.f_GetLen();
	}

	virtual uint64 f_LastAutogeneratedID()
	{
		return m_iLastInsertedID;
	}
};

class CSQLiteQueryInstance : public CQueryInstance
{
private:
	CSQLiteQuery* mp_pQuery;

	struct CParam
	{
		mint m_ParamIndex;

		int m_TypeID;
		CStr m_StrValue;
		union
		{
			int32 m_Int32;
			int64 m_Int64;
			double m_DoubleVal;
		} m_NumericValue;

		CParam()
			: m_ParamIndex(-1)
			, m_TypeID(0)
		{}
	};

	TCVector<CParam> mp_Params;

public:

	CSQLiteQueryInstance(CSQLiteQuery* _pQuery) : mp_pQuery(_pQuery)
	{
		int nParams = sqlite3_bind_parameter_count(mp_pQuery->mp_pStatement);
		mp_Params.f_SetLen(nParams);
	}

	~CSQLiteQueryInstance()
	{
	}

	TCUniquePointer<CQueryResult> f_Execute(sqlite3 *_pSQLite)
	{
		sqlite3_stmt* pStatement = mp_pQuery->mp_pStatement;
		int Ret;

		sqlite3_clear_bindings(pStatement);
		sqlite3_reset(pStatement);

		int nParams = mp_Params.f_GetLen();
		for (int iP = 0; iP < nParams; ++iP)
		{
			CParam const& CurParam = mp_Params[iP];
			Ret = -1;
			switch(CurParam.m_TypeID)
			{
			case 0:
				{
					Ret = sqlite3_bind_null(pStatement, iP + 1);
				}
				break;
			case TCTypeID<CStr>::ETypeID:
				{
					CStr UTF8 = CurParam.m_StrValue;
					Ret = sqlite3_bind_text(pStatement, iP + 1, UTF8.f_GetStr(), -1,  SQLITE_TRANSIENT);
				}
				break;
			case TCTypeID<int32>::ETypeID:
				{
					Ret = sqlite3_bind_int(pStatement, iP + 1, CurParam.m_NumericValue.m_Int32);
				}
				break;
			case TCTypeID<int64>::ETypeID:
				{
					Ret = sqlite3_bind_int64(pStatement, iP + 1, CurParam.m_NumericValue.m_Int64);
				}
				break;
			case TCTypeID<fp64>::ETypeID:
				{
					Ret = sqlite3_bind_double(pStatement, iP + 1, CurParam.m_NumericValue.m_DoubleVal);
				}
				break;
			}

			if (Ret != SQLITE_OK)
			{

				DMibTrace("SQLite execution binding failed: \"\"\n", CStr(sqlite3_errmsg(_pSQLite)));
				return nullptr;
			}
		}


		TCUniquePointer<CSQLiteQueryResult> pResults = fg_Construct();

		Ret = sqlite3_step(pStatement);

		while (Ret == SQLITE_BUSY)
		{
			NSys::fg_Thread_Sleep(0);
			Ret = sqlite3_step(pStatement);
		}

		if (Ret == SQLITE_DONE)
		{
			pResults->m_nAffectedRows = sqlite3_changes(_pSQLite);
			pResults->m_iLastInsertedID = sqlite3_last_insert_rowid(_pSQLite);
			return pResults;
		}

		if (Ret != SQLITE_ROW)
		{
#ifdef DMibDebug
			//CStr ErrMsg = sqlite3_errmsg(_pSQLite);
			//DMibDTrace("SQLite execution failed: \"{}\"\n", ErrMsg);
#endif
			//sqlite3_reset(pStatement);
			return nullptr;
		}

		pResults->m_nAffectedRows = sqlite3_changes(_pSQLite);
		pResults->m_iLastInsertedID = sqlite3_last_insert_rowid(_pSQLite);

		// TODO: Cache this per query where possible (Queries not requiring binding.)

		auto FGetColumnType = [] (int _ColType) -> CQueryResult::EType
		{
			switch(_ColType)
			{
			case SQLITE_INTEGER:
				{
					return CQueryResult::EType_Int64;
				}
				break;
			case SQLITE_FLOAT:
				{
					return CQueryResult:: EType_Fp64;
				}
				break;
			case SQLITE_TEXT:
				{
					return CQueryResult::EType_CStr;
				}
				break;
			case SQLITE_NULL:
				{
					return CQueryResult::EType_NULL;
				}
				break;
			default:
				{
					return CQueryResult::EType_CStr;
				}
				break;
			};
		};

		int nColumns = sqlite3_column_count(pStatement);
		pResults->m_Columns.f_SetLen(nColumns);
		int ColType;
		for (int iC = 0; iC < nColumns; ++iC)
		{
			pResults->m_Columns[iC].m_Name = sqlite3_column_name(pStatement, iC);
			ColType = sqlite3_column_type(pStatement, iC);
			pResults->m_Columns[iC].m_Type = FGetColumnType(ColType);
		}

		pResults->m_nReturnedRows = 0;

		while(Ret == SQLITE_ROW)
		{
			CSQLiteQueryResult::CRow CurRow;
			CurRow.m_Data.f_SetLen(nColumns);

			for (int iC = 0; iC < nColumns; ++iC)
			{
				switch(pResults->m_Columns[iC].m_Type)
				{
				case CQueryResult::EType_Int64:
					CurRow.m_Data[iC] = sqlite3_column_int64(pStatement, iC);
					break;
				case CQueryResult::EType_Fp64:
					{
						double Val = sqlite3_column_double(pStatement, iC);
						CurRow.m_Data[iC] = fp64(Val);
					}
					break;
				case CQueryResult::EType_CStr:
					{
						unsigned char const* pStr = sqlite3_column_text(pStatement, iC);
						if (pStr)
							CurRow.m_Data[iC] = pStr;
						else
							CurRow.m_Data[iC] = CStr();
					}
					break;
				case CQueryResult::EType_NULL:
					{
						// Check to see if this row is non-null.
						int ColType = sqlite3_column_type(pStatement, iC);
						pResults->m_Columns[iC].m_Type = FGetColumnType(ColType);
						if (pResults->m_Columns[iC].m_Type != CQueryResult::EType_NULL)
							--iC;
//						CurRow.m_Data[iC] = (int64)0;
					}
					break;
				}
			}

			pResults->m_Rows.f_Insert(CurRow);
			++pResults->m_nReturnedRows;
			Ret = sqlite3_step(pStatement);
		}

		return pResults;
	}

	virtual bool f_BindParameter(int _iParam, int _TypeID, void const*_pParam)
	{
		if (!mp_Params.f_IsPosValid(_iParam))
			return false;

		CParam& Param = mp_Params[_iParam];

		Param.m_TypeID = _TypeID;

		switch(_TypeID)
		{
		case 0:
			{
				Param.m_TypeID = 0;
			}
			break;
		case TCTypeID<NTime::CTime>::ETypeID:
			{
				Param.m_StrValue = fg_GetFullTimeStr(*(NTime::CTime*)_pParam);
				Param.m_TypeID = TCTypeID<CStr>::ETypeID;
			}
			break;
		case TCTypeID<CStr>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<CStr>::ETypeID;
				Param.m_StrValue = *(CStr*)_pParam;
			}
			break;
		case TCTypeID<CWStr>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<CStr>::ETypeID;
				Param.m_StrValue = *(CWStr*)_pParam;
			}
			break;

		//case TCTypeID<float>::ETypeID:
		//	{
		//		Param.m_TypeID = TCTypeID<double>::ETypeID;
		//		Param.m_NumericValue.m_DoubleVal = *(float*)_pData;
		//	}
		//	break;
		//case TCTypeID<double>::ETypeID:
		//	{
		//		Param.m_NumericValue.m_DoubleVal = *(double*)_pData;
		//	}
		//	break;
		case TCTypeID<fp32>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<fp64>::ETypeID;
				Param.m_NumericValue.m_DoubleVal = (*(fp32*)_pParam).f_Get();
			}
			break;
		case TCTypeID<fp64>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<fp64>::ETypeID;
				Param.m_NumericValue.m_DoubleVal = (*(fp64*)_pParam).f_Get();
			}
			break;

		case TCTypeID<int32>::ETypeID:
			{
				Param.m_NumericValue.m_Int32 = *(int32*)_pParam;
			}
			break;
		case TCTypeID<uint32>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<int64>::ETypeID;
				Param.m_NumericValue.m_Int64 = (int64)*(uint32*)_pParam;
			}
			break;
		case TCTypeID<int64>::ETypeID:
			{
				Param.m_NumericValue.m_Int64 = *(int64*)_pParam;
			}
			break;
		case TCTypeID<uint64>::ETypeID:
			{
				Param.m_TypeID = TCTypeID<int64>::ETypeID;
				Param.m_NumericValue.m_Int64 = *(uint64*)_pParam;
			}
			break;
		default:
			return false;
		}

		return true;
	}

};

NStorage::TCUniquePointer<CQueryInstance> CSQLiteQuery::f_CreateQueryInstance()
{
	NStorage::TCUniquePointer<CSQLiteQueryInstance> pResult = fg_Construct(this);
	return pResult;
}


class CDatabaseImplementation_SQLite : public NMib::NSQL::CDatabaseImplementation
{
private:

	sqlite3 *mp_pDB;

public:

	CDatabaseImplementation_SQLite() : mp_pDB(nullptr)
	{
	}
	~CDatabaseImplementation_SQLite()
	{
		DMibSafeCheck(!mp_pDB, "Must be deleted");
	}

	virtual bool f_Create(const NMib::NContainer::CRegistry &_Parameters)
	{
		DMibCheck(!mp_pDB);

		int Ret;
		CStr DBFile = _Parameters.f_GetValue("Database", "");

		Ret = sqlite3_open(DBFile.f_GetStr(), &mp_pDB);

		if (Ret != SQLITE_OK)
		{
			CStr Error = f_SqlError(0, "Failed to open SQLite DB.");
			DMibConOut("DB error: {}\n", Error);
			DMibTrace("sqlite3_open: {}\n", Error);
			return false;
		}

		return true;
	}

	virtual void f_Destroy(bool _bDestroyThread)
	{
		if (mp_pDB)
		{
			int Ret = sqlite3_close(mp_pDB);
			(void)Ret;
			DMibSafeCheck(Ret != SQLITE_BUSY, "Not all SQLite objects have been destroyed - e.g. statements");
			DMibSafeCheck(Ret == SQLITE_OK, "Failed to destroy SQLite DB.");
			mp_pDB = nullptr;
		}
	}

	CFStr1024 f_SqlError(int _Err, const ch8 *_pError)
	{
		return CFStr1024(_pError) + CFStr1024(" SQLite returned: ") + sqlite3_errmsg(mp_pDB);
	}

	TCUniquePointer<CQuery> f_CreateQuery(NStr::CStr _Query)
	{
//		DMibDTrace("Creating sqlite query: {}\n", _Query);
		sqlite3_stmt* pStatement = nullptr;

		CStr UTF8Query = _Query;

		int Ret;

		while (SQLITE_BUSY == (Ret = sqlite3_prepare_v2(mp_pDB, UTF8Query.f_GetStr(), -1, &pStatement, nullptr)))
		{
			NSys::fg_Thread_Sleep(0);
		};

		if (Ret != SQLITE_OK)
		{
			CStr Error = f_SqlError(0, "Failed to prepare SQLite query.");
			DMibConOut("DB error: {}\n", Error);
			DMibTrace("sqlite3_prepare_v2: {}\n", Error);
			return nullptr;
		}

		TCUniquePointer<CSQLiteQuery> pQuery = fg_Construct(pStatement);
		return pQuery;
	}

	void f_BeginTransaction()
	{
		sqlite3_exec(mp_pDB, "BEGIN TRANSACTION", nullptr, nullptr, nullptr);
	}

	TCUniquePointer<CQueryResult> f_RunQuery(TCUniquePointer<CQueryInstance> const &_pQuery)
	{
		CSQLiteQueryInstance *pInstance = (CSQLiteQueryInstance *)_pQuery.f_Get();

		return pInstance->f_Execute(mp_pDB);
	}

	void f_CommitTransaction()
	{
		sqlite3_exec(mp_pDB, "COMMIT TRANSACTION", nullptr, nullptr, nullptr);
	}

	void f_RollbackTransaction()
	{
		sqlite3_exec(mp_pDB, "ROLLBACK TRANSACTION", nullptr, nullptr, nullptr);
	}

};

DMibRuntimeClassNamedCasted(NMib::NSQL::CDatabaseImplementation, CDatabaseImplementation_SQLite, NMib::NSQL::CDatabaseImplementation_SQLite, NMib::NSQL::CDatabaseImplementation);

void fg_Malterlib_SQL_SQLite_MakeActive()
{
	DMibRuntimeClassMakeActive(CDatabaseImplementation_SQLite);
}
