// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#pragma once

#include <Mib/Core/Core>
#include <Mib/Container/Registry>

namespace NMib::NSQL
{
	class CSQLConnection;
	/*¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯*\
	|	Class:				A Database exception									|
	\*_____________________________________________________________________________*/
	DMibImpErrorClassDefine(CExceptionDatabase, NException::CException);

#	define DMibErrorDatabase(d_Description) DMibImpError(NMib::NSQL::CExceptionDatabase, d_Description)

#	ifndef DMibPNoShortCuts
#		define DErrorDatabase DMibErrorDatabase
#	endif

	//class CQueryResultIterator
	//{
	//public:
	//	virtual int f_GetRowIndex() = 0;
	//
	//	virtual CStr const& f_GetString(int _iCol, CStr &_Dest) = 0;
	//	virtual int64 f_GetInt64(int _iCol) = 0;
	//	virtual fp64 f_GetFp64(int _iCol) = 0;
	//
	//	virtual bool f_Next() = 0;
	//	virtual bool f_OK() = 0;
	//};


	class CQueryResult
	{
	public:
		enum EType
		{
			EType_Int64,
			EType_Fp64,
			EType_CStr,
			EType_NULL,
		};

		struct CCol
		{
			EType m_Type;
			NMib::NStr::CStr m_Name;
		};

	public:
		virtual ~CQueryResult() {}

//			virtual NMib::NStr::CStr const& f_GetString(int _iRow, int _iCol) = 0;
		virtual NMib::NStr::CStr f_GetString(int _iRow, int _iCol) = 0;
		virtual int64 f_GetInt64(int _iRow, int _iCol) = 0;
		virtual fp64 f_GetFp64(int _iRow, int _iCol) = 0;
		virtual bool f_IsNull(int _iRow, int _iCol) = 0;

		virtual NMib::NContainer::TCVector<CCol> const &f_GetFields() = 0;
		virtual EType f_GetFieldType(int _iCol) = 0;
		virtual NMib::NStr::CStr const &f_GetFieldName(int _iCol) = 0;

//			virtual const ch8 *f_GetData(int _iRow, int _iCol) = 0;
//			virtual const NContainer::TCVector<const ch8 *> &f_GetFields() = 0;

		virtual aint f_NumReturnedRows() = 0;
		virtual aint f_NumAffectedRows() = 0;
		virtual aint f_NumFields() = 0;
		virtual uint64 f_LastAutogeneratedID() = 0;
	};

	class CDatabaseImplementation;
	class CQueryInstance;

	class CQuery
	{
	public:

		CQuery();
		virtual ~CQuery();

		virtual NStorage::TCUniquePointer<CQueryInstance> f_CreateQueryInstance() = 0;
	};

	class CQueryInstance
	{
	public:
		virtual ~CQueryInstance()
		{
		}

		virtual bool f_BindParameter(int _iParam, int _TypeID, void const*_pParam) = 0;

		template <typename tf_CType>
		bool f_BindParameter(int _iParam, tf_CType const& _Data)
		{
			return f_BindParameter(_iParam, NMib::NMisc::TCTypeID<tf_CType>::ETypeID, &_Data);
		}

		bool f_BindParameterNull(int _iParam);
	};

	class CTransactionResult
	{
	public:
		NContainer::TCVector<NStorage::TCUniquePointer<CQueryResult>> m_Results;
		~CTransactionResult();
		CQueryResult *f_GetQueryResult(aint _iQuery);
	};

	class CTransaction
	{
	public:
		class CQueryLink
		{
		public:
			DMibListLinkD_Link(CQueryLink, m_Link);
			NStorage::TCUniquePointer<CQueryInstance> m_pQueryInstance;
		};

		DMibListLinkD_List(CQueryLink, m_Link) m_Transactions;
		typedef DMibListLinkD_Iter(CQueryLink, m_Link) CQueryIter;
		int m_nTransactions;
		bool m_bAllowFail;
		NContainer::TCVector<NStorage::TCUniquePointer<CQuery>> m_OwnedQueries;

		~CTransaction();
		CTransaction();
		NStorage::TCUniquePointer<CQueryInstance> const &f_AddQuery(NStorage::TCUniquePointer<CQuery> const &_pQuery);
		void f_SetAllowFail(bool _bAllow);
	};

	typedef void (FTransactionResultCallback)(NStorage::TCUniquePointer<CTransactionResult> const &_pResult, void *_pContext);

	class CDatabaseImplementation
	{
	public:
		virtual ~CDatabaseImplementation(){}

		virtual bool f_Create(const NContainer::CRegistry &_Parameters) = 0;
		virtual void f_Destroy(bool _bDestroyTherad) = 0;
		virtual NStorage::TCUniquePointer<CQuery> f_CreateQuery(NStr::CStr _Query) = 0;

		virtual void f_BeginTransaction() = 0;
		virtual NStorage::TCUniquePointer<CQueryResult> f_RunQuery(NStorage::TCUniquePointer<CQueryInstance> const &_pQuery) = 0;
		virtual void f_CommitTransaction() = 0;
		virtual void f_RollbackTransaction() = 0;
	};


	class CTransactionHandler
	{
	public:
		virtual ~CTransactionHandler();
		static void fs_HandleTransaction(NStorage::TCUniquePointer<CTransactionResult> const &_pResult, void *_pContext);
		virtual void f_HandleTransaction(NStorage::TCUniquePointer<CTransactionResult> const &_pResult) = 0;
	};

	class CSQLConnection
	{
		class CTask
		{
		public:
			CTask(CSQLConnection *_pSQL);
			~CTask();

			DMibListLinkD_Link(CTask, m_Link);

			CSQLConnection *m_pSQL;
			NStorage::TCUniquePointer<CTransaction> m_pTransaction;
			void *m_pContext;
			NThread::CSemaphoreAggregate *m_pEvent;
			FTransactionResultCallback *m_fCallback;
			bool m_bAsync;

			NStorage::TCUniquePointer<CTransactionResult> m_pResult;

			void f_Run(CDatabaseImplementation *_pImp);
		};

		NThread::CMutual mp_QueueLock;
		DMibListLinkD_List(CTask, m_Link) mp_QueuedTasks;
		typedef DMibListLinkD_Iter(CTask, m_Link) CTaskIter;


		void fp_QueueTask(CTask *_pTask);

		NStorage::TCUniquePointer<CTransactionResult> fp_CommitTransaction(NStorage::TCUniquePointer<CTransaction> &&_pTransaction, CDatabaseImplementation *_pImp);

		class CWorkerThread : public NThread::CThread
		{
		public:

			CWorkerThread(CSQLConnection *_pSQL);
			~CWorkerThread();

			NStr::CStr f_GetThreadName() override;
			aint f_Main() override;

			CSQLConnection *m_pSQLConnection;
			DMibListLinkD_Link(CWorkerThread, m_Link);
			CTask *m_pTask = nullptr;
		};

		NThread::CMutual mp_ThreadsLock;
		NThread::CEventAutoReset mp_ThreadEvent;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_DeletedThreads;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_FreeThreads;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_WorkingThreads;

		NStr::CStr mp_Implementation;
		NContainer::CRegistry mp_Parameters;
		NStorage::TCUniquePointer<CDatabaseImplementation> mp_pMainImp;
	public:

		CSQLConnection();
		~CSQLConnection();

		bool f_Create(const ch8 *_pImplementation, const NContainer::CRegistry &_Parameters, mint _nWorkerThreadss);

		void f_Close();

		NStorage::TCUniquePointer<CQuery> f_CreateQuery(const NStr::CStr &_Query);
		NStorage::TCUniquePointer<CTransaction> f_CreateTransaction();
		NStorage::TCUniquePointer<CTransaction> f_CreateTransaction(NStr::CStr const& _Statements);	// Create a transaction from a list of semi-colon separated statements.
		NStorage::TCUniquePointer<CQueryInstance> f_CreateQueryInstance(NStorage::TCUniquePointer<CQuery> const &_pQuery);

		template <typename ...tfp_CParam>
		NStorage::TCUniquePointer<CQueryResult> f_ExecuteBindWithoutTransaction(NStr::CStr const &_Query, tfp_CParam const &...p_Params);
		template <typename ...tfp_CParam>
		NStorage::TCUniquePointer<CQueryResult> f_ExecuteBind(NStr::CStr const &_Query, tfp_CParam const &...p_Params);
		template <typename ...tfp_CParam>
		NStorage::TCUniquePointer<CQueryResult> f_ExecuteBind(NStorage::TCUniquePointer<CQuery> const &_pQuery, tfp_CParam const &...p_Params);

		NStorage::TCUniquePointer<CQueryResult> f_ExecuteQuery(NStorage::TCUniquePointer<CQueryInstance> const &_pQueryInst);

		NStorage::TCUniquePointer<CTransactionResult> f_CommitTransaction(NStorage::TCUniquePointer<CTransaction> &&_pTransaction); // Blocks
		// Async transactions
		void f_CommitTransaction
			(
				NStorage::TCUniquePointer<CTransaction> &&_pTransaction
				, void * _pContext
				, NThread::CSemaphoreAggregate *_pEvent
				, FTransactionResultCallback *_fCallback
				, bool _bAsync
			)
		;

		void f_CommitTransaction(NStorage::TCUniquePointer<CTransaction> &&_pTransaction, CTransactionHandler *_pHandler, NThread::CSemaphoreAggregate *_pEvent, bool _bAsync);
		void f_ProcessTansactions();
	};
}

#ifndef DMibPNoShortCuts
	using namespace NMib::NSQL;
#endif

#include "Malterlib_SQL.hpp"
