// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#pragma once

#include <Mib/Core/Core>
#include <Mib/Container/Registry>

namespace NMib::NSQL
{
	class CSQLConnection;
	/*¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯*\
	|	Class:				A Database exception									|
	\*_____________________________________________________________________________*/
	DMibImpErrorClassDefine(CExceptionDatabase, NException::CException);

#	define DMibErrorDatabase(d_Description) DMibImpError(NMib::NSQL::CExceptionDatabase, d_Description)

#	ifndef DMibPNoShortCuts
#		define DErrorDatabase DMibErrorDatabase
#	endif

	//class CQueryResultIterator
	//{
	//public:
	//	virtual int f_GetRowIndex() = 0;
	//
	//	virtual CStr const& f_GetString(int _iCol, CStr &_Dest) = 0;
	//	virtual int64 f_GetInt64(int _iCol) = 0;
	//	virtual fp64 f_GetFp64(int _iCol) = 0;
	//
	//	virtual bint f_Next() = 0;
	//	virtual bint f_OK() = 0;
	//};


	class CQueryResult
	{
	public:
		enum EType
		{
			EType_Int64,
			EType_Fp64,
			EType_CStr,
			EType_NULL,
		};

		struct CCol
		{
			EType m_Type;
			NMib::NStr::CStr m_Name;
		};

	public:
		virtual ~CQueryResult() {}

//			virtual NMib::NStr::CStr const& f_GetString(int _iRow, int _iCol) = 0;
		virtual NMib::NStr::CStr f_GetString(int _iRow, int _iCol) = 0;
		virtual int64 f_GetInt64(int _iRow, int _iCol) = 0;
		virtual fp64 f_GetFp64(int _iRow, int _iCol) = 0;
		virtual bint f_IsNull(int _iRow, int _iCol) = 0;

		virtual NMib::NContainer::TCVector<CCol> const &f_GetFields() = 0;
		virtual EType f_GetFieldType(int _iCol) = 0;
		virtual NMib::NStr::CStr const &f_GetFieldName(int _iCol) = 0;

//			virtual const ch8 *f_GetData(int _iRow, int _iCol) = 0;
//			virtual const NContainer::TCVector<const ch8 *> &f_GetFields() = 0;

		virtual aint f_NumReturnedRows() = 0;
		virtual aint f_NumAffectedRows() = 0;
		virtual aint f_NumFields() = 0;
		virtual uint64 f_LastAutogeneratedID() = 0;
		virtual void f_Delete() = 0;
	};

	class CDatabaseImplementation;
	class CQueryInstance;

	class CQuery
	{
	public:

		CQuery();
		virtual ~CQuery();

		virtual CQueryInstance *f_CreateQueryInstance() = 0;

		virtual void f_Delete() = 0;
	};

	class CQueryInstance
	{
	public:
		virtual ~CQueryInstance()
		{
		}

		virtual bint f_BindParameter(int _iParam, int _TypeID, void const*_pParam) = 0;

		template <typename tf_CType>
		bint f_BindParameter(int _iParam, tf_CType const& _Data)
		{
			return f_BindParameter(_iParam, NMib::NMisc::TCTypeID<tf_CType>::ETypeID, &_Data);
		}

		bint f_BindParameterNull(int _iParam);

		virtual void f_Delete() = 0;
	};

	class CTransactionResult
	{
	public:
		NContainer::TCVector<CQueryResult *> m_Results;
		~CTransactionResult();
		CQueryResult *f_GetQueryResult(aint _iQuery);
	};

	class CTransaction
	{
	public:
		class CQueryLink
		{
		public:
			DMibListLinkD_Link(CQueryLink, m_Link);
			CQueryInstance *m_pQueryInstance;
			CQueryLink();
			~CQueryLink();
		};

		DMibListLinkD_List(CQueryLink, m_Link) m_Transactions;
		typedef DMibListLinkD_Iter(CQueryLink, m_Link) CQueryIter;
		int m_nTransactions;
		bint m_bAllowFail;
		NContainer::TCVector< NStorage::TCUniquePointer<CQuery> > m_OwnedQueries;

		~CTransaction();
		CTransaction();
		CQueryInstance *f_AddQuery(CQuery *_pQuery);
		void f_Delete();
		void f_SetAllowFail(bint _bAllow);
	};

	typedef void (PFTransactionResultCallback)(CTransactionResult *_pResult, void *_pContext);

	class CDatabaseImplementation
	{
	public:
		virtual ~CDatabaseImplementation(){}

		virtual bint f_Create(const NContainer::CRegistry &_Parameters) = 0;
		virtual void f_Destroy(bint _bDestroyTherad) = 0;
		virtual CQuery *f_CreateQuery(NStr::CStr _Query) = 0;

		virtual void f_BeginTransaction() = 0;
		virtual CQueryResult *f_RunQuery(CQueryInstance *_pQuery) = 0;
		virtual void f_CommitTransaction() = 0;
		virtual void f_RollbackTransaction() = 0;
	};


	class CTransactionHandler
	{
	public:
		virtual ~CTransactionHandler();
		static void fs_HandleTransaction(CTransactionResult *_pResult, void *_pContext);
		virtual void f_HandleTransaction(CTransactionResult *_pResult) = 0;
	};

	class CSQLConnection
	{
		class CTask
		{
		public:
			CTask(CSQLConnection *_pSQL);
			~CTask();

			DMibListLinkD_Link(CTask, m_Link);

			CSQLConnection *m_pSQL;
			CTransaction *m_pTransaction;
			void *m_pContext;
			NThread::CSemaphoreReportableAggregate *m_pEvent;
			PFTransactionResultCallback *m_fCallback;
			bint m_bAsync;

			CTransactionResult *m_pResult;

			void f_Run(CDatabaseImplementation *_pImp);
		};

		NThread::CMutual mp_QueueLock;
		DMibListLinkD_List(CTask, m_Link) mp_QueuedTasks;
		typedef DMibListLinkD_Iter(CTask, m_Link) CTaskIter;


		void fp_QueueTask(CTask *_pTask);

		CTransactionResult *fp_CommitTransaction(CTransaction *_pTransaction, CDatabaseImplementation *_pImp);

		class CWorkerThread : public NThread::CThread
		{
		public:

			CWorkerThread(CSQLConnection *_pSQL);
			~CWorkerThread();

			NStr::CStr f_GetThreadName() override;
			aint f_Main() override;

			CSQLConnection *m_pSQLConnection;
			NThread::CEventAutoResetReportable m_Event;
			DMibListLinkD_Link(CWorkerThread, m_Link);
			CTask *m_pTask;
		};

		NThread::CMutual mp_ThreadsLock;
		NThread::CEventAutoReset mp_ThreadEvent;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_DeletedThreads;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_FreeThreads;
		DMibListLinkD_List(CWorkerThread, m_Link) mp_WorkingThreads;

		NStr::CStr mp_Implementation;
		NContainer::CRegistry mp_Parameters;
		NStorage::TCUniquePointer<CDatabaseImplementation> mp_pMainImp;
	public:

		CSQLConnection();
		~CSQLConnection();

		bint f_Create(const ch8 *_pImplementation, const NContainer::CRegistry &_Parameters, mint _nWorkerThreadss);

		void f_Close();

		CQuery *f_CreateQuery(const NStr::CStr &_Query);
		CTransaction *f_CreateTransaction();
		CTransaction *f_CreateTransaction(NStr::CStr const& _Statements);	// Create a transaction from a list of semi-colon separated statements.
		CQueryInstance *f_CreateQueryInstance(CQuery *_pQuery);

		CQueryResult *f_ExecuteQuery(const NStr::CStr &_Query, bool _bTransaction = true);
		CQueryResult *f_ExecuteQuery(CQueryInstance *_pQueryInst);
		CQueryResult *f_ExecuteQuery(CQuery *_pQuery);

		CTransactionResult *f_CommitTransaction(CTransaction *_pTransaction); // Blocks
		// Async transactions
		void f_CommitTransaction(CTransaction *_pTransaction, void * _pContext, NThread::CSemaphoreReportableAggregate *_pEvent, PFTransactionResultCallback *_fCallback, bint _bAsync);

		void f_CommitTransaction(CTransaction *_pTransaction, CTransactionHandler *_pHandler, NThread::CSemaphoreReportableAggregate *_pEvent, bint _bAsync);


		void f_ProcessTansactions();

	};
}

#ifndef DMibPNoShortCuts
	using namespace NMib::NSQL;
#endif

