// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

/***********************************************************************************

NOTE: Parameter binding (CQueryInstance::f_BindParameter) is NOT supported for MySql.

************************************************************************************/

#include <Mib/SQL/SQL>
#include <Mib/Storage/Variant>
#include <Mib/Core/RuntimeType>

#ifdef DPlatformFamily_Windows
	#include <windows.h>
#endif

#include <mysql.h>
#include <errmsg.h>

using namespace NMib;
using namespace NSQL;
using namespace NStr;
using namespace NContainer;

class CMySqlQuery;

class CMySqlQueryResult : public CQueryResult
{

public:

	typedef NMib::NStorage::TCVariant<int64, fp64, CStr> CValue;

	struct CRow
	{
		TCVector<CValue> m_Data;
	};

	aint m_nReturnedRows;
	aint m_nAffectedRows;
	aint m_nFields;
	uint64 m_iLastInsertedID;

	TCVector<CCol> m_Columns;
	TCVector<CRow> m_Rows;

public:
	CMySqlQueryResult()
	{
		m_nReturnedRows = 0;
		m_nAffectedRows = 0;
		m_nFields = 0;
	}

	//virtual CStr const& f_GetString(int _iRow, int _iCol)
	virtual CStr f_GetString(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return CStr();

		switch(m_Columns[_iCol].m_Type)
		{
		case EType_CStr:
			return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<CStr>();
		case EType_Int64:
			return (CStr::CFormat("{}") << m_Rows[_iRow].m_Data[_iCol].f_GetAsType<int64>());
		case EType_Fp64:
			return (CStr::CFormat("{}") << m_Rows[_iRow].m_Data[_iCol].f_GetAsType<CStr>());
		default:
			return CStr();
		}
	}

	virtual int64 f_GetInt64(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return 0;

		DMibRequire(m_Columns[_iCol].m_Type == EType_Int64);
		return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<int64>();
	}

	virtual fp64 f_GetFp64(int _iRow, int _iCol)
	{
		DMibRequire(m_Rows.f_IsPosValid(_iRow) && m_Columns.f_IsPosValid(_iCol));

		if (m_Columns[_iCol].m_Type == EType_NULL)
			return 0;

		DMibRequire(m_Columns[_iCol].m_Type == EType_Fp64);
		return m_Rows[_iRow].m_Data[_iCol].f_GetAsType<fp64>();
	}

	virtual bool f_IsNull(int _iRow, int _iCol)
	{
		return m_Columns[_iCol].m_Type == EType_NULL;
	}


	virtual TCVector<CCol> const &f_GetFields()
	{
		return m_Columns;
	}

	virtual EType f_GetFieldType(int _iCol)
	{
		return m_Columns[_iCol].m_Type;
	}

	virtual CStr const &f_GetFieldName(int _iCol)
	{
		return m_Columns[_iCol].m_Name;
	}

	virtual aint f_NumReturnedRows()
	{
		return m_nReturnedRows;
	}

	virtual aint f_NumAffectedRows()
	{
		return m_nAffectedRows;
	}

	virtual aint f_NumFields()
	{
		return m_Columns.f_GetLen();
	}

	virtual uint64 f_LastAutogeneratedID()
	{
		return m_iLastInsertedID;
	}
	void f_Delete()
	{
		delete this;
	}
};

class CMySqlQueryInstance : public CQueryInstance
{
public:
	CMySqlQuery *m_pQuery;
	CStr m_Error;

	CMySqlQueryInstance()
	{
	}

	~CMySqlQueryInstance()
	{
	}

	void f_Delete()
	{
		delete this;
	}


	CQueryResult *f_Execute(NMib::NSQL::CDatabaseImplementation *_pImp);

	virtual bool f_BindParameter(int _iParam, int _TypeID, void const*_pParam)
	{
		DMibSafeCheck(false, "Parameter binding is NOT supported for MySql currently.");
		return false;
	}
};


class CMySqlQuery : public CQuery
{
public:
	CStr m_Statement;
	CMySqlQuery()
	{
	}
	~CMySqlQuery()
	{
	}

	void f_Delete()
	{
		delete this;
	}

	virtual CQueryInstance *f_CreateQueryInstance()
	{
		CMySqlQueryInstance *pQueryInst = DMibNew CMySqlQueryInstance;
		pQueryInst->m_pQuery = this;
		return pQueryInst;
	}
};

class CDatabaseImplementation_MySql : public NMib::NSQL::CDatabaseImplementation
{
public:

	CDatabaseImplementation_MySql()
	{
	}
	~CDatabaseImplementation_MySql()
	{
		DMibSafeCheck(!m_pConn, "Must be deleted");
	}

	class CMainThreadCleanup
	{
	public:
		bool m_bDoneInit;
		CMainThreadCleanup()
		{
			m_bDoneInit = false;
//			mysql_thread_init();
		}

		~CMainThreadCleanup()
		{
//			MYSQL *pSql = mysql_init(nullptr);
//			mysql_close(pSql);
//			mysql_thread_end();
			if (m_bDoneInit)
				mysql_server_end();
		}
	};
	static CMainThreadCleanup ms_MainThreadCleanup;

	MYSQL m_Conn;
	MYSQL *m_pConn;

	virtual bool f_Create(const NMib::NContainer::CRegistry &_Parameters)
	{
        m_pConn = mysql_init(&m_Conn);
		ms_MainThreadCleanup.m_bDoneInit = true;

		if (m_pConn)
		{
			CStr Host = _Parameters.f_GetValue("Host", "");
			CStr User = _Parameters.f_GetValue("User", "");
			CStr Password = _Parameters.f_GetValue("Password", "");
			CStr Database = _Parameters.f_GetValue("Database", "");
			int Port = _Parameters.f_GetValue("Port", "0").f_ToInt();
			MYSQL *pSQL = mysql_real_connect(m_pConn, Host!=""?Host.f_GetStr():nullptr, User!=""?User.f_GetStr():nullptr, Password!=""?Password.f_GetStr():nullptr, Database!=""?Database.f_GetStr():nullptr, Port, nullptr, 0);

			if (pSQL)
			{
				mysql_autocommit(pSQL, 0);
				return true;
			}
			else
			{
				CStr Error = f_SqlError(0, "Failed to connect.");
				DMibConOut("Connect error: {}\n", Error);
				DMibTrace("mysql_real_connect: {}\n", Error);

				f_Destroy(false);
				return false;
			}
		}
		else
			return false;
	}

	virtual void f_Destroy(bool _bDestroyThread)
	{
		if (m_pConn)
		{
			mysql_close(m_pConn);

			if (_bDestroyThread)
				mysql_thread_end();

			m_pConn = nullptr;
		}
	}

	CFStr1024 f_SqlError(int _Err, const ch8 *_pError)
	{
		return CFStr1024(_pError) + CFStr1024(" MySql returned: ") + mysql_error(m_pConn);
	}


	CQuery *f_CreateQuery(NStr::CStr _Query)
	{
		CMySqlQuery *pQuery = DMibNew CMySqlQuery;
		pQuery->m_Statement = _Query;
		return pQuery;
	}

	void f_BeginTransaction()
	{
	}

	CQueryResult *f_RunQuery(CQueryInstance *_pQuery)
	{
		CMySqlQueryInstance *pInstance = (CMySqlQueryInstance *)_pQuery;

		return pInstance->f_Execute(this);
	}

	void f_CommitTransaction()
	{
		mysql_commit(m_pConn);
	}

	void f_RollbackTransaction()
	{
		mysql_rollback(m_pConn);
	}

};

CDatabaseImplementation_MySql::CMainThreadCleanup CDatabaseImplementation_MySql::ms_MainThreadCleanup;

DMibRuntimeClassNamedCasted(NMib::NSQL::CDatabaseImplementation, CDatabaseImplementation_MySql, NMib::NSQL::CDatabaseImplementation_MySql, NMib::NSQL::CDatabaseImplementation);


CQueryResult *CMySqlQueryInstance::f_Execute(NMib::NSQL::CDatabaseImplementation *_pImp)
{
	CDatabaseImplementation_MySql *pImp = (CDatabaseImplementation_MySql *)_pImp;

#if 0
	MYSQL_STMT *pStatement = mysql_stmt_init(pImp->m_pConn);
	int Err = mysql_stmt_prepare(pStatement, m_pQuery->m_Statement.f_GetCStrLossy(), m_pQuery->m_Statement.f_GetLen());
	if (Err)
	{
		DMibErrorDatabase(pImp->f_SqlError(Err, "Failed to prepare statement."));
	}

	Err = mysql_stmt_execute(pStatement);
	if (Err)
	{
		mysql_stmt_close(pStatement);

		m_Error = pImp->f_SqlError(Err, "Failed to execute statement.");
		return nullptr;
	}

	CMyQueryResult *pResult = DNew CMyQueryResult;

	int nParams = mysql_stmt_param_count(pStatement);
	pResult->m_nReturedRows;

	mysql_stmt_close(pStatement);
#else
	int Err = mysql_real_query(pImp->m_pConn, CStr(m_pQuery->m_Statement), m_pQuery->m_Statement.f_GetLen());
	if (Err)
	{
		uint32 MyErr = mysql_errno(pImp->m_pConn);
		if (MyErr == CR_SERVER_LOST)
			Err = mysql_real_query(pImp->m_pConn, CStr(m_pQuery->m_Statement), m_pQuery->m_Statement.f_GetLen()); // Try to reconnect

		if (Err)
		{
			m_Error = pImp->f_SqlError(Err, "Failed to execute statement.");
			DMibConOut("Query error: {}\n", m_Error);
			DMibTrace("mysql_real_query: {}\n", m_Error);
			return nullptr;
		}
	}

	CMySqlQueryResult *pResult = DMibNew CMySqlQueryResult;

	pResult->m_nAffectedRows = mysql_affected_rows(pImp->m_pConn);
	MYSQL_RES *pRes = mysql_store_result(pImp->m_pConn);

	if (pRes)
	{
		pResult->m_nReturnedRows = mysql_num_rows(pRes);
		pResult->m_iLastInsertedID = mysql_insert_id(pImp->m_pConn);

		int nFields = mysql_num_fields(pRes);
		MYSQL_FIELD *pFields = mysql_fetch_fields(pRes);
		pResult->m_Columns.f_SetLen(nFields);

		for(int i = 0; i < nFields; ++i)
		{
			NMib::NSQL::CQueryResult::CCol &CurCol = pResult->m_Columns[i];
			CurCol.m_Name = pFields[i].name;
			switch(pFields[i].type)
			{
			case MYSQL_TYPE_SHORT:
			case MYSQL_TYPE_LONG:
				{
					CurCol.m_Type = NMib::NSQL::CQueryResult::EType_Int64;
				}
				break;
			case MYSQL_TYPE_FLOAT:
			case MYSQL_TYPE_DOUBLE:
				{
					CurCol.m_Type = NMib::NSQL::CQueryResult::EType_Fp64;
				}
				break;

			case MYSQL_TYPE_VAR_STRING:
			case MYSQL_TYPE_STRING:
				{
					CurCol.m_Type = NMib::NSQL::CQueryResult::EType_CStr;
				}
				break;

			case MYSQL_TYPE_NULL:
			case MYSQL_TYPE_TIMESTAMP:
			case MYSQL_TYPE_LONGLONG:
			case MYSQL_TYPE_INT24:
			case MYSQL_TYPE_DATE:
			case MYSQL_TYPE_TIME:
			case MYSQL_TYPE_DATETIME:
			case MYSQL_TYPE_YEAR:
			case MYSQL_TYPE_NEWDATE:
			case MYSQL_TYPE_ENUM:
			case MYSQL_TYPE_SET:
			case MYSQL_TYPE_TINY_BLOB:
			case MYSQL_TYPE_MEDIUM_BLOB:
			case MYSQL_TYPE_LONG_BLOB:
			case MYSQL_TYPE_BLOB:
			case MYSQL_TYPE_GEOMETRY:
				{
					CurCol.m_Type = NMib::NSQL::CQueryResult::EType_CStr;
				}
				break;
			default:
				{
					CurCol.m_Type = NMib::NSQL::CQueryResult::EType_CStr;
				}
				break;
			}
			pResult->m_Columns[i].m_Name = pFields[i].name;
		}
		pResult->m_Rows.f_SetLen(pResult->m_nReturnedRows);

		int iRow = 0;

		MYSQL_ROW ppRow;

		while ((ppRow = mysql_fetch_row(pRes)) && iRow < pResult->m_nReturnedRows)
		{
			//						unsigned long *pLengths;
			//						pLengths = mysql_fetch_lengths(result);
			pResult->m_Rows[iRow].m_Data.f_SetLen(nFields);

			for(int i = 0; i < nFields; i++)
			{
				if (ppRow[i])
				{
					switch(pResult->m_Columns[i].m_Type)
					{
					case NMib::NSQL::CQueryResult::EType_Int64:
						pResult->m_Rows[iRow].m_Data[i] = CStr(ppRow[i]).f_ToInt<int64>(0);
						break;
					case NMib::NSQL::CQueryResult::EType_Fp64:
						pResult->m_Rows[iRow].m_Data[i] = CStr(ppRow[i]).f_ToFloat<fp64>(0.0);
						break;
					case NMib::NSQL::CQueryResult::EType_CStr:
						pResult->m_Rows[iRow].m_Data[i] = CStr(ppRow[i]);
						break;
					case NMib::NSQL::CQueryResult::EType_NULL:
						DMibNeverGetHere;
						break;
					}
				}
			}
			++iRow;
		}

		mysql_free_result(pRes);
	}
	else
	{
		if(mysql_field_count(pImp->m_pConn) == 0)
		{
			pResult->m_iLastInsertedID = mysql_insert_id(pImp->m_pConn);
		}
		else // mysql_store_result() should have returned data
		{
			DMibErrorDatabase(pImp->f_SqlError(Err, "Failed to produce result with mysql_store_result."));
		}
	}
#endif


	return pResult;
}

void fg_Malterlib_SQL_MySql_MakeActive()
{
	DMibRuntimeClassMakeActive(CDatabaseImplementation_MySql);
}
